name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        pip install ruff mypy
        
    - name: Run ruff
      run: ruff check src/
      continue-on-error: true
      
    - name: Run mypy
      run: mypy src/
      continue-on-error: true


